//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Converter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class PythonMethods
        ///{
        ///	private static Dictionary&lt;char, int&gt; SymbolNumberPairs = new Dictionary&lt;char, int&gt;
        ///		{
        ///			{&apos;0&apos;, 0 },
        ///			{&apos;1&apos;, 1 }, {&apos;2&apos;, 2 }, {&apos;3&apos;, 3 },
        ///			{&apos;4&apos;, 4 }, {&apos;5&apos;, 5 }, {&apos;6&apos;, 6 },
        ///			{&apos;7&apos;, 7 }, {&apos;8&apos;, 8 }, {&apos;9&apos;, 9 },
        ///		};
        ///
        ///	public static IEnumerable&lt;dynamic&gt; Range(dynamic start, dynamic stop, dynamic step)
        ///	{
        ///		dynamic i = start;
        ///
        ///		while ((i &lt; stop &amp;&amp; step &gt;= 0) || (i &gt; stop &amp;&amp; step &lt;= 0))
        ///		{
        ///			yield return i;
        ///
        ///			i += step;
        ///		}
        ///	}
        ///
        ///	public static IEnumerable&lt;dynamic&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PythonMethods {
            get {
                return ResourceManager.GetString("PythonMethods", resourceCulture);
            }
        }
    }
}
